// app/layout.tsx

export const metadata = {
  title: 'Eschaton Storefront',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}// If you place it in styles/globals.css
import '../styles/globals.css';

