// app/layout.tsx
import './globals.css' // Or your actual CSS file
import type { ReactNode } from 'react'

export const metadata = {
  title: 'Eschaton Storefront',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
